### ISSUE TITLE
Adding a CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [mariogarridopt/xBar-Uptime-Kuma#18]
Adding a new file for a general Code Of Conduct

**Comment by mariogarridopt** [comment]
I don't think we need a code of conduct.

I expect people to behave in a respectful way with everyone, and I don't want to create limits to communication.

With this said, there are limits, and those are common sense. And I will enforce those limits as a moderator of the conversation.

**Comment by the-amazing-atharva** [comment]
No worries!
