### ISSUE TITLE
Create contributing instructions

### ISSUE THREAD

**Issue by mariogarridopt** [mariogarridopt/xBar-Uptime-Kuma#2]
A `CONTRIBUTING.md` file with instructions on how to contribute to this project is always very helpful.
I have done something like this before here: [CONTRIBUTING.md](https://github.com/mariogarridopt/Saphira/blob/master/CONTRIBUTING.md).

But I'm not an expert.

**The good thing is: if you search here on GitHub for `CONTRIBUTING.md` you find many examples.**

**Comment by the-amazing-atharva** [comment]
Hi, I am a beginner here and would like to add a contributing section!

**Comment by mariogarridopt** [comment]
**Sounds great!**

This is a new project, there is no code here yet, but it will be soon. A Python Script, close to this [example](https://github.com/matryer/xbar-plugins/blob/main/Dev/utimerobot.30s.py), but for [UptimeKuma](https://github.com/louislam/uptime-kuma).

A `CONTRIBUTING.md` file with the instructions on how to contribute to this project is always very helpful.
I have done something like this before here: [CONTRIBUTING.md](https://github.com/mariogarridopt/Saphira/blob/master/CONTRIBUTING.md). But I'm not an expert.
The good thing is: if you search here on GitHub for `CONTRIBUTING.md` you find many examples.

Since we don't have instructions to contribute, your current contribution will work this way:
- Fork this repository;
- Make your changes (aka: create CONTRIBUTING.md)
- Make a pull request to send your changes from the fork to this repo;
- I will review the pull request and merge your changes.

**Any questions let me know.**

**Comment by the-amazing-atharva** [comment]
Thanks for the reply!!

Will this work or do I need to reduce the number of points?
![image](https://user-images.githubusercontent.com/121221252/214339712-ea1b31d5-b026-494f-961b-5667a18e731a.png)

**Comment by mariogarridopt** [comment]
Looks great for me ^^

**Comment by the-amazing-atharva** [comment]
Ok, will send a PR in sometime :)

**Comment by mariogarridopt** [comment]
Just more examples:
- https://github.com/github/docs/blob/7a67b66a84d7b368e9bc981f11f89ff61c06e792/CONTRIBUTING.md

**Comment by the-amazing-atharva** [comment]
Do I add the list in the README or CONTRIBUTING.md?

**Comment by mariogarridopt** [comment]
Create CONTRIBUTING.md file with good instructions on how to contribute

**Comment by the-amazing-atharva** [comment]
Sure!

**Comment by the-amazing-atharva** [comment]
Hey!!

If you liked the file, do merge the PR so if there are any further upgrades it would be easier to understand
